# 시각화

In [130]:
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set() # setting seaborn default for plots

def bar_chart(feature):
    yes = train[train['voted']==1][feature].value_counts()
    no = train[train['voted']==2][feature].value_counts()
    df = pd.DataFrame([yes,no])
    df.index = ['Yes','No']
    df.plot(kind='bar',stacked=True, figsize=(10,5))

In [131]:
import pandas as pd

train=pd.read_csv('./train.csv')
test=pd.read_csv('./test_x.csv')

# 데이터 전처리

In [132]:
import numpy as np
train['trust']=1
test['trust']=1

family_drop_score=10

train['trust']=np.where(train['familysize'] >= family_drop_score, 0, train['trust'])
test['trust']=np.where(test['familysize'] >= family_drop_score, 0, test['trust'])

train['trust']=np.where(train['education'] == 0, 0, train['trust'])
train['education']=np.where(train['education'] == 0, 2, train['education'])
test['trust']=np.where(test['education'] == 0, 0, test['trust'])
test['education']=np.where(test['education'] == 0, 2, test['education'])

train['urban']=train['urban'].astype('str')
test['urban']=test['urban'].astype('str')

train['education']=train['education'].astype('str')
test['education']=test['education'].astype('str')

In [133]:
time = ['QaE', 'QbE', 'QcE', 'QdE', 'QeE','QfE', 'QgE', 'QhE', 'QiE', 'QjE', 'QkE', 'QlE', 'QmE', 'QnE', 'QoE', 'QpE', 'QqE', 'QrE', 'QsE', 'QtE']

train[time] = np.where(train[time] > 10000, 10000, train[time])
test[time] = np.where(test[time] > 10000, 10000, test[time])

# train[time] = np.where(train[time] > 10000, train[time].median(), train[time])
# test[time] = np.where(test[time] > 10000, test[time].median(), test[time])

P_time=['QbE', 'QcE', 'QhE', 'QjE', 'QmE', 'QoE', 'QpE', 'QsE', 'QtE']
N_time=['QaE', 'QdE', 'QeE', 'QfE', 'QgE', 'QiE', 'QkE', 'QlE', 'QnE', 'QqE', 'QrE']

train['p_time']=train[P_time].sum(axis=1)
test['p_time']=test[P_time].sum(axis=1)
train['n_time']=train[N_time].sum(axis=1)
test['n_time']=test[N_time].sum(axis=1)

# 원핫 인코딩 (gender, race, religion)

In [134]:
train=pd.get_dummies(train, columns=['race'])
train=pd.get_dummies(train, columns=['religion'])
train=pd.get_dummies(train, columns=['gender'])
train=pd.get_dummies(train, columns=['urban'])
train=pd.get_dummies(train, columns=['education'])
train=pd.get_dummies(train, columns=['age_group'])
train=pd.get_dummies(train, columns=['hand'])

test=pd.get_dummies(test, columns=['race'])
test=pd.get_dummies(test, columns=['religion'])
test=pd.get_dummies(test, columns=['gender'])
test=pd.get_dummies(test, columns=['urban'])
test=pd.get_dummies(test, columns=['education'])
test=pd.get_dummies(test, columns=['age_group'])
test=pd.get_dummies(test, columns=['hand'])

# Feature : Mach_score (마키아벨리니즘 스코어)

In [135]:
Answers = ['QaA', 'QbA', 'QcA', 'QdA', 'QeA',
             'QfA', 'QgA', 'QhA', 'QiA', 'QjA', 
             'QkA', 'QlA', 'QmA', 'QnA', 'QoA', 
             'QpA', 'QqA', 'QrA', 'QsA', 'QtA']

In [136]:
reverse = ["QeA", "QfA", "QkA", "QqA", "QrA"]
for r in reverse: 
        train[r] = 6 - train[r]
        test[r] = 6 - test[r]

In [137]:
reverse = ["QaA", "QdA", "QgA", "QiA", "QnA"]
for r in reverse: 
        train[r] = 6 - train[r]
        test[r] = 6 - test[r]

In [138]:
train['Mach_score'] = train[Answers].mean(axis = 1)
test['Mach_score'] = test[Answers].mean(axis = 1)

# Feature : tp0106, tp0207, tp0308, tp0409, tp0510 (관련있는 tp 끼리 묶음)

In [139]:
Tp = ['tp01', 'tp02', 'tp03', 'tp04', 'tp05',
             'tp06', 'tp07', 'tp08', 'tp09', 'tp10']

In [140]:
reverse = ["tp06", "tp07", "tp08", "tp09", "tp10"]
for r in reverse: 
        train[r] = 7 - train[r]
        test[r] = 7 - test[r]
        
tp0106=['tp01', 'tp06']
tp0207=['tp02', 'tp07']
tp0308=['tp03', 'tp08']
tp0409=['tp04', 'tp09']
tp0510=['tp05', 'tp10']
train['tp0106'] = train[tp0106].sum(axis = 1)
train['tp0207'] = train[tp0207].sum(axis = 1)
train['tp0308'] = train[tp0308].sum(axis = 1)
train['tp0409'] = train[tp0409].sum(axis = 1)
train['tp0510'] = train[tp0510].sum(axis = 1)
temp=['tp0106', 'tp0207', 'tp0308','tp0409', 'tp0510']

test['tp0106'] = test[tp0106].sum(axis = 1)
test['tp0207'] = test[tp0207].sum(axis = 1)
test['tp0308'] = test[tp0308].sum(axis = 1)
test['tp0409'] = test[tp0409].sum(axis = 1)
test['tp0510'] = test[tp0510].sum(axis = 1)

In [141]:
train[temp].describe()

             tp0106        tp0207        tp0308        tp0409        tp0510
count  45532.000000  45532.000000  45532.000000  45532.000000  45532.000000
mean       7.545023      7.590090      5.261486      7.763749      4.017921
std        3.509913      2.916658      3.043976      3.366161      2.473560
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        5.000000      6.000000      3.000000      5.000000      2.000000
50%        8.000000      8.000000      5.000000      8.000000      4.000000
75%       11.000000     10.000000      7.000000     11.000000      6.000000
max       14.000000     14.000000     14.000000     14.000000     14.000000

In [142]:
tp_drop_score=12

train['trust']=np.where(train['tp0106'] >= tp_drop_score, 0, train['trust'])
train['trust']=np.where(train['tp0207'] >= tp_drop_score, 0, train['trust'])
train['trust']=np.where(train['tp0308'] >= tp_drop_score, 0, train['trust'])
train['trust']=np.where(train['tp0409'] >= tp_drop_score, 0, train['trust'])
train['trust']=np.where(train['tp0510'] >= tp_drop_score, 0, train['trust'])

test['trust']=np.where(test['tp0106'] >= tp_drop_score, 0, test['trust'])
test['trust']=np.where(test['tp0207'] >= tp_drop_score, 0, test['trust'])
test['trust']=np.where(test['tp0308'] >= tp_drop_score, 0, test['trust'])
test['trust']=np.where(test['tp0409'] >= tp_drop_score, 0, test['trust'])
test['trust']=np.where(test['tp0510'] >= tp_drop_score, 0, test['trust'])

train['tp0106']=np.where(train['tp0106'] >= tp_drop_score, tp_drop_score, train['tp0106'])
train['tp0207']=np.where(train['tp0207'] >= tp_drop_score, tp_drop_score, train['tp0207'])
train['tp0308']=np.where(train['tp0308'] >= tp_drop_score, tp_drop_score, train['tp0308'])
train['tp0409']=np.where(train['tp0409'] >= tp_drop_score, tp_drop_score, train['tp0409'])
train['tp0510']=np.where(train['tp0510'] >= tp_drop_score, tp_drop_score, train['tp0510'])

test['tp0106']=np.where(test['tp0106'] >= tp_drop_score, tp_drop_score, test['tp0106'])
test['tp0207']=np.where(test['tp0207'] >= tp_drop_score, tp_drop_score, test['tp0207'])
test['tp0308']=np.where(test['tp0308'] >= tp_drop_score, tp_drop_score, test['tp0308'])
test['tp0409']=np.where(test['tp0409'] >= tp_drop_score, tp_drop_score, test['tp0409'])
test['tp0510']=np.where(test['tp0510'] >= tp_drop_score, tp_drop_score, test['tp0510'])

# wf_(1~3) : 설문자의 어휘 능력 (허구인 단어의 정의를 앎)

In [143]:
wf=['wf_01', 'wf_02', 'wf_03']

train['wf']=train[wf].mean(axis=1)
train['trust']= np.where(train['wf'] >= 0.0, 0, train['trust'])

test['wf']=test[wf].mean(axis=1)
test['trust']= np.where(test['wf'] >= 0.0, 0, test['trust'])

# drop 할 feature들

In [144]:
drop_feature=[
#                 'engnat',
    
#                 'familysize',
    
#                 'married',
    
#                 'race_Arab', 'race_Asian','race_Black','race_Indigenous Australian','race_Native American','race_Other','race_White',               
    
                'religion_Agnostic','religion_Atheist', 'religion_Buddhist','religion_Christian_Catholic','religion_Christian_Mormon', 
                'religion_Christian_Other', 'religion_Christian_Protestant', 'religion_Hindu','religion_Jewish','religion_Muslim', 
                'religion_Other','religion_Sikh',
    
#                 'gender_Female','gender_Male',
                
#                 'urban_0','urban_1','urban_2','urban_3',
    
#                 'education_1', 'education_2', 'education_3', 'education_4'
                
#                 'age_group_+70s','age_group_10s','age_group_20s','age_group_30s','age_group_40s','age_group_50s','age_group_60s'
                
                'QaA', 'QbA', 'QcA', 'QdA', 'QeA','QfA', 'QgA', 'QhA', 'QiA', 'QjA', 'QkA', 'QlA', 'QmA', 'QnA', 'QoA','QpA', 
                'QqA', 'QrA', 'QsA', 'QtA',
                
                'QaE', 'QbE', 'QcE', 'QdE', 'QeE', 'QfE', 'QgE', 'QhE', 'QiE', 'QjE', 'QkE', 'QlE','QmE', 'QnE', 'QoE', 'QpE', 
                'QqE', 'QrE', 'QsE', 'QtE',
    
#                 'p_time' , 

                'n_time',
              
                'tp01', 'tp02', 'tp03', 'tp04', 'tp05','tp06','tp07', 'tp08', 'tp09', 'tp10',
              
                'wr_01', 'wr_02', 'wr_03', 'wr_04', 'wr_05', 'wr_06', 'wr_07', 'wr_08', 'wr_09','wr_10','wr_11', 'wr_12', 'wr_13', 
                'wf_01', 'wf_02', 'wf_03', 'wf',
              
                'hand_0','hand_1','hand_2','hand_3',
              
              ]

train = train.drop(drop_feature, axis = 1)
test = test.drop(drop_feature, axis = 1)

# Model 생성

In [145]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

# 사용한 feature 목록

In [146]:
for i in train:
    print(i)

index
engnat
familysize
married
voted
trust
p_time
race_Arab
race_Asian
race_Black
race_Indigenous Australian
race_Native American
race_Other
race_White
gender_Female
gender_Male
urban_0
urban_1
urban_2
urban_3
education_1
education_2
education_3
education_4
age_group_+70s
age_group_10s
age_group_20s
age_group_30s
age_group_40s
age_group_50s
age_group_60s
Mach_score
tp0106
tp0207
tp0308
tp0409
tp0510

# Auto ML

In [147]:
from pycaret.classification import *
clf = setup(data = train, target = 'voted',ignore_features=['index'])

# 모델 학습 및 비교 (Train models and compare)

In [148]:
best_3 = compare_models(sort = 'AUC', n_select = 3)

In [149]:
tuned_best_3=[tune_model(i, fold=10, round=4, n_iter=10, custom_grid = None, optimize = 'AUC', choose_better = True, verbose = False) for i in best_3]

# 모델 앙상블 (Model Ensemble)

In [150]:
blender_best3 = blend_models(estimator_list = tuned_best_3, fold = 5, method = 'soft')

# 모델 예측 (Prediction)

In [151]:
pred_holdout = predict_model(blender_best3)

# 전체 데이터에 대한 재학습 (Re-training the model on whole data)

In [152]:
final_model = finalize_model(blender_best3)

In [153]:
pred_holdout = predict_model(final_model)

# 대회용 test set에 대한 예측 (Predicting on test set for the competition)

In [154]:
print("train :",train.shape)
print("test :",test.shape)

train : (45532, 37)
test : (11383, 36)

In [155]:
predictions = predict_model(final_model, data = test)
predictions

,engnat,familysize,married,p_time,race_Arab,race_Asian,race_Black,race_Indigenous Australian,race_Native American,race_Other,...,age_group_50s,age_group_60s,Mach_score,tp0106,tp0207,tp0308,tp0409,tp0510,Label,Score
0,2.0,3.0,1.0,29074.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.45,7.0,6.0,5.0,7.0,4.0,2,0.5962
1,2.0,2.0,1.0,15497.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,2.80,7.0,7.0,7.0,7.0,7.0,2,0.6394
2,2.0,7.0,2.0,10899.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,3.55,12.0,7.0,8.0,3.0,12.0,2,0.5154
3,1.0,4.0,2.0,12223.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,3.35,1.0,12.0,3.0,12.0,1.0,1,0.5859
4,1.0,3.0,1.0,8982.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.90,12.0,3.0,7.0,5.0,7.0,2,0.6072
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11378,2.0,3.0,1.0,8368.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,3.20,4.0,6.0,7.0,6.0,2.0,2,0.5138
11379,2.0,1.0,1.0,6097.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,4.55,3.0,7.0,9.0,1.0,3.0,2,0.6541
11380,1.0,4.0,2.0,7994.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,3.15,9.0,8.0,2.0,12.0,3.0,1,0.5721
11381,1.0,3.0,2.0,22938.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,3.05,9.0,12.0,2.0,12.0,2.0,1,0.5535
11382,2.0,2.0,1.0,20619.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,3.40,8.0,9.0,4.0,2.0,1.0,2,0.5707

In [156]:
submission= pd.read_csv('./sample_submission.csv')

In [157]:
submission['voted'] = predictions['Label']

In [158]:
submission.to_csv('submission_proba.csv', index = False)

In [159]:
submission['voted'].describe()

count    11383.000000
mean         1.534920
std          0.498801
min          1.000000
25%          1.000000
50%          2.000000
75%          2.000000
max          2.000000
Name: voted, dtype: float64

In [160]:
submission['voted']

0        2
1        2
2        2
3        1
4        2
        ..
11378    2
11379    2
11380    1
11381    1
11382    2
Name: voted, Length: 11383, dtype: int8

In [161]:
submission['voted'].value_counts()

2    6089
1    5294
Name: voted, dtype: int64

# TEST Set에 대한 AUC

In [162]:
from pycaret.utils import check_metric
check_metric(pred_holdout['voted'], pred_holdout['Label'], metric='AUC')

0.7136